### ISSUE TITLE
Broke my app on production

### ISSUE THREAD

**Issue by ChenMorSays** [tannerlinsley/react-charts#112] opened 2020-08-17 14:40 UTC
Any ideas how I may debug this one?

Only receiving the following error after building for production,
but not locally on debug mode.

<img width="500" alt="Screen Shot 2020-08-17 at 17 40 31" src="https://user-images.githubusercontent.com/3942479/90408635-c3ad4580-e0b0-11ea-8e9b-3598a7276458.png">

**Comment by EladBezalel** [comment] 2020-08-18 08:55
Hey @ChenMorSays,
I think it would be better if you'd reproduce it in codesandbox.io, I think it will be hard to understand the issue without seeing the code.

**Comment by ChenMorSays** [comment] 2020-08-18 10:17
How would you recommend reproducing it in production mode, on codesandbox.io?

**Comment by EladBezalel** [comment] 2020-08-18 12:31
Let's start by having the problematic code, there are some ways to make codesandbox to compile code :)

**Comment by githubjonas** [comment] 2020-08-18 16:41
I have the very same problem. By invoking: `yarn encore production` my application won't start as soon as I add the line `import { Chart } from 'react-charts';` anywhere in my application. No other code is needed to replicate the problem.

`yarn encore dev` works, though.

**Comment by ChenMorSays** [comment] 2020-08-18 16:42
@EladBezalel trying to replicate on codesandbox but no success yet.

@githubjonas good news (that I'm not alone here).

Any ideas?

**Comment by githubjonas** [comment] 2020-08-18 16:44
> @EladBezalel trying to replicate on codesandbox but no success yet.
> 
> @githubjonas good news (that I'm not alone here).
> 
> Any ideas?

I'll clone the react-charts code and start debugging. No luck yet. I'll keep you posted. Right now I need to revert to get production working again! :-D

**Comment by githubjonas** [comment] 2020-08-18 20:04
Ok I gave up for now and intermittently went back to `react-google-charts`, but it would be nice to find some solution for this. Sorry I could not give you any more clues, @ChenMorSays .

**Comment by ChenMorSays** [comment] 2020-08-18 20:12
@githubjonas that's a bummer.
Did you try a specific version? Perhaps 2.0.7 beta is not a good release

**Comment by ChenMorSays** [comment] 2020-08-19 07:51
If anyone else comes across this issue, try `yarn add "react-charts@v2.0.2-next.6"` instead.
Worked for us.

**Comment by willhamilton24** [comment] 2020-09-25 15:21
+1 I'm having the same issue

**Comment by tannerlinsley** [comment] 2020-09-25 15:45
Closing this since there is not a reproduction case. Please reopen your issue with a codesandbox that illustrates the bug.

**Closed by tannerlinsley** 2020-09-25 15:45 UTC
Labels: bug
